# change the version number to "0.17.1" or "0.18" in case of a release build
package:
  name: pythonocc-core
  version: 0.18.2

source:
  path: ../..


build:
  script_env:
    - CC
    - CXX

  number: {{ GIT_DESCRIBE_NUMBER }}
  binary_relocation: false [osx]
  features:
    - vc9               [win and py27]
    - vc14              [win and py35]
    - vc14              [win and py36]

requirements:
  build:
    - python
    - oce ==0.18.2
    - cmake ==3.9.3
    - ninja ==1.8.2
    - swig ==3.0.12
    - freetype ==2.7
    - smesh ==6.7.5

  run:
    - pyqt >=5
    - oce ==0.18.2
    - python
    - freetype ==2.7
    - smesh ==6.7.5

test:
  requires:
    - scipy
    - wxpython          [py27]
    - pyside            [py27]
    - smesh ==6.7.5
    - pythreejs ==0.4.1

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package
